server:
  port: 8080

# this can be rewritten to use a secret manager for environment
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:hello-world-chart-mysql.hello-world.svc.cluster.local}:3306/mydatabase
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:YourSecurePassword123}
    admin-username: ${DB_ADMIN_USERNAME:admin}
    admin-password: ${DB_ADMIN_PASSWORD:YourSecureAdminPassword123}
    mysql-root-username: ${DB_ADMIN_USERNAME:root}
    MYSQL_ROOT_PASSWORD: ${DB_ADMIN_PASSWORD:YourSecureAdminPassword123}
    mysql_root_password: ${DB_ADMIN_PASSWORD:YourSecureAdminPassword123}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect