apiVersion: v2
name: hello-world-chart
description: A Helm chart for Kubernetes
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: 11.1.7
    repository: "https://charts.bitnami.com/bitnami"