replicaCount: 1

image:
  repository: anmobor/toni
  tag: latest
  pullPolicy: IfNotPresent

namespace: hello-world

serviceAccount:
  create: true
  automount: true
  name: "hello-world-sac"

securityContext: {}

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-world.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

service:
  type: ClusterIP
  port: 8080

livenessProbe:
  path: "/actuator/health/liveness"
  port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  path: "/actuator/health/readiness"
  port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

mysql:
  auth:
    rootPassword: YourSecurePassword123
    database: mydatabase
    username: admin
    password: YourSecurePassword123
  primary:
    service:
      port: 3306

env:
  DB_HOST: hello-world-chart-mysql.default.svc.cluster.local
  DB_USERNAME: admin
  DB_PASSWORD: YourSecurePassword123
  DB_ADMIN_USERNAME: admin
  DB_ADMIN_PASSWORD: YourSecureAdminPassword123