replicaCount: 1

image:
  repository: anmobor/toni
  tag: latest
  pullPolicy: IfNotPresent

namespace: hello-world

serviceAccount:
  create: true
  automount: true
  name: "hello-world-sac"

deployment:
  annotations: []

rbac:
  create: true

securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-world.192.168.49.2.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

livenessProbe:
  path: /health
  port: 8080
  timeoutSeconds: 5
  periodSeconds: 5
  failureThreshold: 20
  initialDelaySeconds: 120
  successThreshold: 1

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 20
  periodSeconds: 7
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

mysql:
  auth:
    rootPassword: YourSecurePassword123
    database: mydatabase
    username: admin
    password: YourSecurePassword123
  primary:
    service:
      port: 3306

env:
  DB_HOST: hello-world-chart-mysql.hello-world.svc.cluster.local
#  DB_HOST: hello-world-chart-mysql
  DB_USERNAME: admin
  DB_PASSWORD: YourSecurePassword123
  DB_ADMIN_USERNAME: admin
  DB_ADMIN_PASSWORD: YourSecureAdminPassword123

metrics:
  enabled: true
  serviceMonitor:
    enabled: false
    namespace: ~
    additionalLabels: { }
    scrapeInterval: 10s
    honorLabels: false
