name: CI Pipeline

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Lint Code
        run: mvn checkstyle:check

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean compile

      - name: Run tests with Maven
        run: mvn --batch-mode verify

      - name: Run JaCoCo Coverage
        run: mvn jacoco:report

      - name: SonarQube Scan
        with:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar
        continue-on-error: true
        timeout-minutes: 4

      - name: OWASP Dependency-Check
        with:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn org.owasp:dependency-check-maven:check -Ddependency-check.nvd.api.key=${{ secrets.NVD_API_KEY }}
        continue-on-error: true
        timeout-minutes: 4


  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with Jib
        run: mvn compile com.google.cloud.tools:jib-maven-plugin:3.2.1:build -Dimage=dockerhub.com/anmobor/toni:latest
        timeout-minutes: 5

  scan-and-tag-docker:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy Vulnerability Scanner
        run: |
          docker pull dockerhub.com/anmobor/toni:latest
          docker run --rm aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL dockerhub.com/anmobor/toni:latest
          timeout-minutes: 4

      - name: Tag Docker Image
        run: |
          docker tag dockerhub.com/anmobor/toni:latest dockerhub.com/anmobor/toni:${{ github.sha }}

      - name: Push Docker Tag
        run: |
          docker push dockerhub.com/anmobor/toni:${{ github.sha }}

  trufflehog-scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: TruffleHog Secret Scanning
        run: docker run --rm -v "${{ github.workspace }}:/workspace" trufflesecurity/trufflehog:latest filesystem /workspace --only-verified